### ISSUE TITLE
It's stopped working

### ISSUE THREAD

**Issue by ghost** [Gashmore1/PingPongELO#6]
????

**Comment by CharlieGarnham** [comment]
am also hitting this... please fix urgently

**Comment by ghost** [comment]
please fix this, my family are dying

**Comment by Roomsycakes01** [comment]
Cant believe this made it into prod

**Comment by kianoushakbari93** [comment]
I am having the same issue which the browser keep spinning. Is this the same for everyone?

**Comment by Gashmore1** [comment]
The service is running again just a brief hardware failure over the weekend

**Comment by ghost** [comment]
yeah, well your brief hardware failure caused a brief fun failure
